import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Header from "../component/Header/Header";
import Link from "next/link";
import page2 from "./page2";
import Screen from "../component/Screen/Screen";

import client from "../lib/client";

const data = `*[_type=='screen'] {
  title,
  "videoUrl": vid.asset->url
}`;

export default function Home({ information }) {
  console.log(information);
  const info = { information };
  return (
    <div className={styles.container}>
      <Head>
        <title>my next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Screen info={information} />
    </div>
  );
}
export async function getStaticProps() {
  const information = await client.fetch(data);
  return {
    props: {
      information,
    },
  };
}
